export interface Hero {
  title: string;
  subtitle: string;
  lead: string;
}

export interface ProfessionalSummary {
  description: string;
  coreStrengths: string[];
}

export interface TechnicalCategory {
  title: string;
  description: string;
}

export interface TechnicalExpertise {
  categories: TechnicalCategory[];
}

export interface FeaturedProject {
  title: string;
  company: string;
  year: string;
  description: string;
}

export interface OriginStory {
  paragraphs: string[];
}

export interface ContactLink {
  label: string;
  url: string;
}

export interface Contact {
  links: ContactLink[];
}

export interface AboutData {
  hero: Hero;
  professionalSummary: ProfessionalSummary;
  technicalExpertise: TechnicalExpertise;
  featuredProjects: FeaturedProject[];
  originStory: OriginStory;
  contact: Contact;
}

const aboutData: AboutData = {
  hero: {
    title: 'About Me',
    subtitle: 'Software Engineer',
    lead: "I'm Matthew Gerstman, and I've been building things on the internet since I was 9 years old.",
  },
  professionalSummary: {
    description:
      'I want to own features end-to-end. Give me a problem, let me talk to users, and I will build and ship a solution that works. I thrive on impact, from conception to deployment. I care about craft: robust systems, modern tech, and interfaces that feel right. I want to set a high bar for UX, especially in emerging spaces like agent products where we define "good." I identify what is broken and fix it.',
    coreStrengths: [
      'End-to-end feature ownership and product development',
      'User research and product discovery',
      'Modern frontend architecture and performance',
      'UX design for emerging technologies',
      'Systems thinking and problem solving',
    ],
  },
  technicalExpertise: {
    categories: [
      {
        title: 'Languages & Frameworks',
        description:
          'TypeScript, JavaScript, React, Redux, Node.js, Python, Go, Backbone, NextJS',
      },
      {
        title: 'Specializations',
        description:
          'Frontend platforms, Real-time collaboration, Complex data visualization, State management, API design, Developer experience',
      },
      {
        title: 'Leadership & Process',
        description:
          'Technical mentorship, Community building (JS Guild at Dropbox), Migration planning, Cross-functional coordination',
      },
    ],
  },
  featuredProjects: [
    {
      title: 'Notebooks 2.0',
      company: 'Datadog',
      year: '2024',
      description:
        'Led team to ship complete rebuild of collaborative data science tooling with real-time multi-user editing.',
    },
    {
      title: 'Frontend Platform Team',
      company: 'Bluecore',
      year: '2021-2022',
      description:
        'Built frontend north star, migrated component library to TypeScript, shipped autogenerated API client, began NextJS migration.',
    },
    {
      title: 'JS Guild',
      company: 'Dropbox',
      year: '2018',
      description:
        'Co-founded frontend engineering community, bringing together siloed engineers and establishing best practices.',
    },
    {
      title: 'React/Redux Web App',
      company: 'TodayTix',
      year: '2016',
      description:
        'Built greenfield webapp with React, Redux, and functional programming patterns. Learned frontend craft here.',
    },
  ],
  originStory: {
    paragraphs: [
      "I got started when my friend's older brother was building a game called 'Falldown' in C++. I thought it was the coolest thing in the world. He gave me a learn Visual Basic 5 CD set and I built my first program, a generic guest book for websites.",
      'At ten I started learning HTML and JavaScript to build websites to show people at school. I built interactive sites where users could enter their name and get personalized messages.',
      'My favorite site I built was a DBZ dance party site. It was like the hamster dance, but with Dragon Ball Z gifs and music from Ocarina of Time. I wish I still had that code.',
      'TechTV had a huge impact on me. I loved The Screen Savers and even called in a few times. I saw Kevin Mitnick talked about the art of deception and how social engineering works. I watched Pirates of Silicon Valley repeatedly. My childhood heroes were Jobs and Wozniak.',
      'Going into 8th grade a new school opened up, Don Estridge High Tech Middle. I was only there for one year, but it gave me opportunities I never would have dreamed of. I got to take programming in Pascal, Computer Hardware, and a class where I did IT support for teachers.',
      'I kept it up in high school. I charged adults to fix their computers and had about 10 clients. I had a job doing IT for a local medical company. I organized a team to QA their new website.',
      'In summer 2008 I was lucky enough to attend a program at Johns Hopkins University. I took two courses: Programming 1 and Philosophy. Programming 1 was a deeper dive into computer science fundamentals, solidifying my academic understanding. The Philosophy course, surprisingly, taught me critical thinking and logical reasoning skills that proved invaluable in approaching complex technical problems.',
      'From 2009 to 2013, I pursued a Computer Science degree at the University of Florida. I also continued to apply my skills by contracting WordPress websites for various clients. The highlight of my college career was Dance Marathon, where by my senior year I was running technology for the whole event.',
      'My first internship and real job was at Zetta, a startup that did cloud backup for enterprise in Sunnyvale California. The most senior people came from Netscape and I got to hear lots of cool war stories from that era. I was hungry to learn and took time outside of work to learn Go and Backbone. I brought these technologies into work.',
      'I landed at TodayTix in 2015, where I learned frontend development. In 2016 I got to work on a greenfield webapp using React, Redux, and Lodash. We were really into functional programming and played code golf trying to get things down to as few lines as possible. During my time in NYC I saw 250 theater performances.',
      'I loved Dropbox from the moment it was released. I pitched myself as a frontend expert when the company was historically infra-heavy. I had so much imposter syndrome when I joined. The thing I am still proudest of is the JS Guild - me and a couple of other people built a community for frontend engineers who were previously in silos.',
      'I had a really ambitious mandate at Bluecore: "Go build out a frontend platform team." I built features, wrote their frontend north star, migrated their component library to TypeScript, shipped an autogenerated API client, and began a migration from a python monolith to NextJS. Unfortunately there was a leadership shakeup and I lost funding.',
      'I wanted the Datadog job so bad. They are doing some of the best frontend work in the industry. The UI is incredibly complex, data-dense, and interactive. This was the first time I was nowhere near the best frontend engineer at the company. I was thrilled to be in the middle of the pack. I spent 2.5 years in the graphing org, first as an engineer on Dashboards, then learning to manage on Notebooks.',
      'This year I got to celebrate all of the Jewish holidays, which does not happen often. I am grateful to be taking a few months off. But I am also restless, so I am lining up the next thing. I want to build something important and work with amazing people.',
    ],
  },
  contact: {
    links: [
      {
        label: 'Blog: matthewgerstman.com',
        url: 'https://matthewgerstman.com',
      },
      {
        label: 'GitHub: github.com/matthew-gerstman',
        url: 'https://github.com/matthew-gerstman',
      },
      {
        label: 'LinkedIn: linkedin.com/in/matthewgerstman',
        url: 'https://linkedin.com/in/matthewgerstman',
      },
    ],
  },
};

export default aboutData;
