import React from 'react';
import { Link } from 'react-router-dom';
import { GradientText } from '../../components/GradientText';
import { JobCard } from '../../components/JobCard';
import styles from './Career.module.css';

export const Career: React.FC = () => {
  return (
    <div className={styles.container}>
      <header className={styles.hero}>
        <GradientText as="h1">Matthew Gerstman</GradientText>
        <p className={styles.subtitle}>Software Engineer</p>
        <p className={styles.lead}>
          Over 12 years building complex, performant systems that make sophisticated technology feel simple. 
          I specialize in bridging powerful capabilities with production-ready interfaces, with a proven track 
          record of leading technical initiatives from concept to full rollout at scale companies.
        </p>
      </header>

      <section className={styles.section}>
        <h2>Professional Summary</h2>
        <p>
          Frontend Product Engineer with deep full-stack experience, focused on building systems that scale 
          across teams and organizations. I thrive at the intersection of complex technical challenges and 
          user experience, with particular expertise in making non-deterministic systems feel reliable and trustworthy.
        </p>
        
        <div className={styles.strengths}>
          <h3>Core Strengths</h3>
          <ul>
            <li>Systems thinking and scalable architecture design</li>
            <li>Performance engineering and optimization</li>
            <li>Technical leadership and knowledge sharing</li>
            <li>End-to-end product ownership</li>
            <li>Migration expertise and organizational change management</li>
          </ul>
        </div>
      </section>

      <section className={styles.section}>
        <h2>Career Timeline</h2>
        
        <JobCard
          company="Datadog"
          title="Senior Software Engineer"
          period="September 2022 - Present"
          description="Leading development of collaborative data science tooling and dashboard infrastructure. Focus on real-time collaboration, PDF reporting systems, and frontend platform improvements."
          detailsLink="/career/datadog"
          projects={[
            {
              title: "Notebooks 2.0",
              year: "2024",
              description: "Complete rebuild of collaborative data science tooling with real-time multi-user editing and complex notebook interactions at scale.",
              tags: ["TypeScript", "React", "Real-time Collaboration"]
            },
            {
              title: "PDF Reporting System",
              year: "2023",
              description: "Built horizontally scalable Node.js/Puppeteer system for dashboard PDF generation.",
              impact: "Widget fidelity: 70% → 100% (~10x improvement)",
              tags: ["Node.js", "Puppeteer", "gRPC"]
            },
            {
              title: "Dashboard Type Safety Initiative",
              year: "2023-2024",
              description: "Systematic TypeScript migration across dashboards codebase.",
              impact: "Cut TypeScript 'any' usage by 50%",
              tags: ["TypeScript", "Code Quality"]
            }
          ]}
        />

        <JobCard
          company="Bluecore"
          title="Staff Engineer"
          period="June 2021 - September 2022"
          description="Led frontend platform architecture, TypeScript migration, and component library modernization for marketing technology platform."
          detailsLink="/career/bluecore"
          projects={[
            {
              title: "TypeScript Migration & Component Library",
              year: "2021-2022",
              description: "Led migration of entire component library to TypeScript with modern CSS architecture and design system principles.",
              tags: ["TypeScript", "React", "Design Systems"]
            },
            {
              title: "Autogenerated API Client",
              year: "2021",
              description: "Built autogenerated API client system with gRPC/HTTP transcoding for seamless protocol translation.",
              impact: "Eliminated manual API maintenance",
              tags: ["gRPC", "Code Generation"]
            },
            {
              title: "Weekly TypeScript & React Training",
              year: "2021-2022",
              description: "Designed and taught comprehensive training curriculum for entire engineering team.",
              tags: ["Teaching", "Mentorship"]
            }
          ]}
        />

        <JobCard
          company="Dropbox"
          title="Software Engineer → Senior Software Engineer"
          period="June 2017 - June 2021"
          description="Architected Redux state management systems, led frontend architecture for greenfield applications, and founded JavaScript Guild for organizational best practices."
          detailsLink="/career/dropbox"
          projects={[
            {
              title: "Redux State Management System",
              year: "2018",
              description: "Designed comprehensive Redux architecture with TypeScript type-safe patterns adopted across the organization.",
              impact: "Adopted by ~10 teams across ~25 features",
              tags: ["Redux", "TypeScript", "Architecture"]
            },
            {
              title: "Plus Plus: Family Plans & Life Vault",
              year: "2020",
              description: "Led end-to-end frontend architecture for new product line with complex family sharing features.",
              impact: "Created new revenue stream",
              tags: ["Product Engineering", "React"]
            },
            {
              title: "JavaScript Guild",
              year: "2017-2021",
              description: "Founded JavaScript Guild and organized 100+ attendee technical summits for frontend engineers.",
              tags: ["Community", "Leadership"]
            }
          ]}
        />

        <JobCard
          company="TodayTix"
          title="Software Engineer"
          period="January 2016 - June 2017"
          description="Full-stack development for theater ticketing platform. Achieved 95% page load reduction and built complete React + Redux application from scratch."
          detailsLink="/career/todaytix"
          projects={[
            {
              title: "Page Load Optimization",
              year: "2016",
              description: "Comprehensive performance profiling and systematic optimization of mobile-first theater ticketing app.",
              impact: "95% reduction: 8 seconds → 400ms",
              tags: ["Performance", "Webpack"]
            },
            {
              title: "Web 2.0: React + Redux Rebuild",
              year: "2016",
              description: "Built production-ready React + Redux application from scratch with comprehensive component library.",
              tags: ["React", "Redux", "Greenfield"]
            },
            {
              title: "Special Offers Feature",
              year: "2016",
              description: "End-to-end feature design converting users who lost lottery into alternative sales.",
              impact: "New revenue stream from lost sales",
              tags: ["Product Engineering", "Full-Stack"]
            }
          ]}
        />

        <JobCard
          company="Zetta.net"
          title="Intern → Software Engineer"
          period="June 2012 - December 2015"
          description="Cloud storage platform development. Led SVN → Git migration, established CI/CD practices, and built core data lifecycle features."
          detailsLink="/career/zetta"
          projects={[
            {
              title: "Backbone + RESTful APIs Migration",
              year: "2015",
              description: "Led complete backend migration to RESTful architecture and frontend migration to Backbone.js.",
              impact: "First major technical leadership role",
              tags: ["Migration", "Architecture"]
            },
            {
              title: "SVN → Git Migration",
              year: "2015",
              description: "Planned and executed organizational migration with team training and code review processes.",
              tags: ["Git", "Change Management"]
            },
            {
              title: "Data Restore Flow",
              year: "2014",
              description: "Built complete data restore flow with intuitive UI for version history and conflict resolution.",
              impact: "Core revenue-driving feature",
              tags: ["Product Engineering", "UI/UX"]
            }
          ]}
        />

        <JobCard
          company="Dance Marathon at University of Florida"
          title="Technology Captain → Technology Overall Director"
          period="September 2010 - April 2013"
          description="Led technology strategy for one of the largest student-run philanthropies. Built engagement apps used by thousands of participants for 5+ years."
          detailsLink="/career/dance-marathon"
          projects={[
            {
              title: "DMAssassins",
              year: "2012",
              description: "Real-life 'assassins' game with target assignment system keeping thousands engaged throughout 26.6-hour marathon.",
              impact: "Used by thousands for 5+ years",
              tags: ["PHP", "MySQL", "Game Design"]
            },
            {
              title: "Tweet Two Screens",
              year: "2013",
              description: "Custom tweet visualizers optimized for Jumbotron display with real-time aggregation.",
              tags: ["Twitter API", "Real-time"]
            },
            {
              title: "DMatUF iPhone App",
              year: "2013",
              description: "Native iOS event app with schedule, song requests, and arena map for offline-first usage.",
              tags: ["iOS", "Native Mobile"]
            }
          ]}
        />
      </section>

      <section className={styles.section}>
        <h2>Technical Expertise</h2>
        <div className={styles.techGrid}>
          <div className={styles.techCategory}>
            <h4>Languages & Frameworks</h4>
            <p>TypeScript, JavaScript, React, Redux, Node.js, Python, PHP, SQL</p>
          </div>
          <div className={styles.techCategory}>
            <h4>Specializations</h4>
            <p>Real-time collaboration systems, Complex UI, Performance optimization, State management at scale, API architecture</p>
          </div>
          <div className={styles.techCategory}>
            <h4>Leadership & Process</h4>
            <p>Technical mentorship, Migration planning, Community building, Cross-functional coordination</p>
          </div>
        </div>
        <Link to="/career/skills" className={styles.btn}>Full Skills & Philosophy →</Link>
      </section>

      <section className={styles.section}>
        <h2>Origin Story</h2>
        <p>
          Started programming at age 11 with Visual Basic, driven by curiosity about how programs work. 
          Built websites at 12, explored networking protocols at 13, and ran a freelance tech support 
          business in high school.
        </p>
        <p>
          Won the Don Estridge Award for technical achievement in middle school. Formal CS education 
          covered algorithms, data structures, and hardware fundamentals. Early experiences emphasized 
          deep technical understanding, strong communication, and user empathy—principles that continue 
          to shape my work today.
        </p>
      </section>

      <section className={styles.section}>
        <h2>Contact & Links</h2>
        <ul className={styles.contactLinks}>
          <li><a href="https://matthewgerstman.com">Blog: matthewgerstman.com</a></li>
          <li><a href="https://github.com/matthewgerstman">GitHub: github.com/matthewgerstman</a></li>
          <li><a href="https://linkedin.com/in/matthewgerstman">LinkedIn: linkedin.com/in/matthewgerstman</a></li>
        </ul>
      </section>
    </div>
  );
};
